### ISSUE TITLE
Missing Hint

### ISSUE THREAD

**Issue by rcoh** [jrvidal/explaine.rs#10]
### What I expected
`::` is the path separator (https://doc.rust-lang.org/book/appendix-02-operators.html)

### Source code
```
 4 |     let list_tables = ListTablesOperation::new().limit(50).build(dynamo_config);
   |                                          ↑

 9 | }
```

Location: line 4, column 41

**Comment by jrvidal** [comment]
This is now deployed :+1: Thanks for the suggestion!
