### ISSUE TITLE
Generated links don't work

### ISSUE THREAD

**Issue by tguser402** [jrvidal/explaine.rs#2]
Generated links don't work. Here is a link I've just generated:
[https://jrvidal.github.io/?code=fn%20main()%7B%7D](https://jrvidal.github.io/?code=fn%20main()%7B%7D)
I get error 404 when I try to access it.

It looks like the correct link should be
[https://jrvidal.github.io/explaine.rs/?code=fn%20main()%7B%7D](https://jrvidal.github.io/explaine.rs/?code=fn%20main()%7B%7D)

**Comment by jrvidal** [comment]
Thanks for the report :raised_hands: I just deployed a fix.
