### ISSUE TITLE
Tapping doesn't work

### ISSUE THREAD

**Issue by programmerjake** [jrvidal/explaine.rs#4]
Tapping on text doesn't seem to work.

I'm on Chrome for Android.
Chrome v80.0.3987.162
Android 9

**Comment by jrvidal** [comment]
:wave: Thanks for the report! Right now I haven't been able to test mobile much, tough I tried to make it usable.

I've just uploaded a new release that includes some error reporting. Would you mind trying again to see if I get a stacktrace I can debug? Thanks!
