### ISSUE TITLE
"may not" is misleading

### ISSUE THREAD

**Issue by stefnotch** [jrvidal/explaine.rs#45]
> ?Sized Trait Bound
> 
> A bound that expresses that the Sized trait may not be implemented for a given type parameter.

is what the website says. I think it should say "may or may not" instead, like in [the Rust book](https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait).

**Comment by jrvidal** [comment]
Good point! Care to send a PR? :grimacing:
